package com.batteryforensics.database.mapper

import com.batteryforensics.core.model.MonitoringSample
import com.batteryforensics.database.entity.MonitoringSampleEntity

fun MonitoringSampleEntity.toDomain(): MonitoringSample = MonitoringSample(
    timestampEpochMs = timestampEpochMs,
    batteryPercent = batteryPercent,
    voltageMv = voltageMv,
    currentMicroamps = currentMicroamps,
    chargeCounterMah = chargeCounterMah,
    temperatureC = temperatureC,
    isCharging = isCharging,
    chargePlug = chargePlug,
    screenOn = screenOn,
    brightnessPercent = brightnessPercent,
    refreshRateHz = refreshRateHz,
    thermalStatus = thermalStatus,
    wifiConnected = wifiConnected,
    wifiRssiDbm = wifiRssiDbm,
    cellularRssiDbm = cellularRssiDbm,
    networkType = networkType,
    chargingCurrentMicroamps = chargingCurrentMicroamps,
    orientation = orientation,
    cellId = cellId,
    carrierName = carrierName,
    cellularBand = cellularBand,
    bluetoothOn = bluetoothOn,
    bluetoothConnected = bluetoothConnected,
    locationEnabled = locationEnabled,
    nfcEnabled = nfcEnabled,
    hotspotOn = hotspotOn,
    foregroundApp = foregroundApp,
    memoryPressure = memoryPressure,
    storageFreeBytes = storageFreeBytes,
    storageFreePercent = storageFreePercent,
    hdrActive = hdrActive,
)

fun MonitoringSample.toEntity(): MonitoringSampleEntity = MonitoringSampleEntity(
    timestampEpochMs = timestampEpochMs,
    batteryPercent = batteryPercent,
    voltageMv = voltageMv,
    currentMicroamps = currentMicroamps,
    chargeCounterMah = chargeCounterMah,
    temperatureC = temperatureC,
    isCharging = isCharging,
    chargePlug = chargePlug,
    screenOn = screenOn,
    brightnessPercent = brightnessPercent,
    refreshRateHz = refreshRateHz,
    thermalStatus = thermalStatus,
    wifiConnected = wifiConnected,
    wifiRssiDbm = wifiRssiDbm,
    cellularRssiDbm = cellularRssiDbm,
    networkType = networkType,
    chargingCurrentMicroamps = chargingCurrentMicroamps,
    orientation = orientation,
    cellId = cellId,
    carrierName = carrierName,
    cellularBand = cellularBand,
    bluetoothOn = bluetoothOn,
    bluetoothConnected = bluetoothConnected,
    locationEnabled = locationEnabled,
    nfcEnabled = nfcEnabled,
    hotspotOn = hotspotOn,
    foregroundApp = foregroundApp,
    memoryPressure = memoryPressure,
    storageFreeBytes = storageFreeBytes,
    storageFreePercent = storageFreePercent,
    hdrActive = hdrActive,
)
